// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
//
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

#include "datadog/impl/crash_reporting/data/crash_context_read.hpp"

#include "datadog/impl/core/storage/path.hpp"
#include "datadog/impl/core/storage/filesystem_wrapper.hpp"
#include "datadog/impl/crash_reporting/data/crash_context_write.hpp"

#include "mock/filesystem.hpp"
#include "support/catch.hpp"
#include "support/crash_data.hpp"

using namespace datadog;
using namespace datadog::impl;

TEST_CASE("ReadCrashContext", "[unit][crash_reporting]") {
  // Given a mock filesystem
  MockFilesystem fs;

  // And binary data generated by writing a representative CrashContext using
  // WriteCrashContext, so that ReadCrashContext has data to parse in test sections below
  PlatformPath write_path;
  PlatformPath write_tmp_path;
  REQUIRE(write_path.Encode("crash.ctx"));
  REQUIRE(write_tmp_path.Encode("crash.ctx.tmp"));
  const CrashContext mock_ctx = MakeMockCrashContext();
  REQUIRE(WriteCrashContext(fs, write_path, write_tmp_path, mock_ctx));
  const std::string binary_string{fs.Cat("crash.ctx")};
  const std::string_view data{binary_string};

  SECTION("M parse crash context file and return expected field values") {
    // Given a file that contains our generated crash context data
    fs.Touch("ctx.bin", data);

    // And an open handle to that file
    const bool hold_advisory_lock = false;
    auto open_res = fs.Wrapper().OpenForRead("ctx.bin", hold_advisory_lock);
    REQUIRE(open_res.value == FilesystemResult::OK);

    // When we parse that file as crash context
    auto result = ReadCrashContext(open_res.file);

    // Then we get a valid result value
    REQUIRE(result.GetStatus() == ReadCrashContextResult::Status::OK);
    REQUIRE(result.data.has_value());
    REQUIRE(result.fs_result == FilesystemResult::OK);

    // And all fields contain the values encoded in the mock data
    const CrashContext& got = *result.data;
    REQUIRE(got.service == mock_ctx.service);
    REQUIRE(got.env == mock_ctx.env);
    REQUIRE(got.application_version == mock_ctx.application_version);
    REQUIRE(got.source == mock_ctx.source);
    REQUIRE(got.sdk_version == mock_ctx.sdk_version);
    REQUIRE(got.tracking_consent == mock_ctx.tracking_consent);
    REQUIRE(got.os_name == mock_ctx.os_name);
    REQUIRE(got.os_version == mock_ctx.os_version);
    REQUIRE(got.os_build == mock_ctx.os_build);
    REQUIRE(got.os_version_major == mock_ctx.os_version_major);
    REQUIRE(got.device_type == mock_ctx.device_type);
    REQUIRE(got.device_name == mock_ctx.device_name);
    REQUIRE(got.device_model == mock_ctx.device_model);
    REQUIRE(got.device_brand == mock_ctx.device_brand);
    REQUIRE(got.device_architecture == mock_ctx.device_architecture);
    REQUIRE(got.device_locale == mock_ctx.device_locale);
    REQUIRE(got.device_time_zone == mock_ctx.device_time_zone);
    REQUIRE(got.user_id == mock_ctx.user_id);
    REQUIRE(got.user_name == mock_ctx.user_name);
    REQUIRE(got.user_email == mock_ctx.user_email);
    REQUIRE(got.user_extra_json == mock_ctx.user_extra_json);
    REQUIRE(
        got.rum_session_state.session_id == mock_ctx.rum_session_state.session_id
    );
    REQUIRE(got.rum_session_state.is_sampled == mock_ctx.rum_session_state.is_sampled);
    REQUIRE(got.rum_session_state.is_active == mock_ctx.rum_session_state.is_active);
    REQUIRE(
        got.rum_session_state.is_initial_session ==
        mock_ctx.rum_session_state.is_initial_session
    );
    REQUIRE(
        got.rum_session_state.has_tracked_any_view ==
        mock_ctx.rum_session_state.has_tracked_any_view
    );
    REQUIRE(got.last_view_event_json == mock_ctx.last_view_event_json);
    REQUIRE(got.global_attributes_json == mock_ctx.global_attributes_json);
  }

  SECTION("M return no value W file has invalid header magic") {
    // Given a file that contains garbage data
    fs.Touch("crash.ctx", "hello-world-this-file-is-not-a-valid-crash-report");

    // And an open handle to that file
    const bool hold_advisory_lock = false;
    auto open_res = fs.Wrapper().OpenForRead("crash.ctx", hold_advisory_lock);
    REQUIRE(open_res.value == FilesystemResult::OK);

    // When we parse that file as crash context
    auto result = ReadCrashContext(open_res.file);
    REQUIRE(result.fs_result == FilesystemResult::OK);

    // Then we get no value
    REQUIRE(result.GetStatus() == ReadCrashContextResult::Status::Malformed);
    REQUIRE(!result.data.has_value());
  }

  SECTION("M return no value W file has invalid footer magic") {
    // Given a file that contains valid crash context data, with the exception of having
    // garbage data in place of the final value
    const std::string_view data_less_8_bytes{data.data(), data.size() - 8};
    fs.Touch("crash.ctx", std::string(data_less_8_bytes) + "badfooter");

    // And an open handle to that file
    const bool hold_advisory_lock = false;
    auto open_res = fs.Wrapper().OpenForRead("crash.ctx", hold_advisory_lock);
    REQUIRE(open_res.value == FilesystemResult::OK);

    // When we parse that file as crash context
    auto result = ReadCrashContext(open_res.file);

    // Then we get no value
    REQUIRE(!result.data.has_value());
    REQUIRE(result.GetStatus() == ReadCrashContextResult::Status::Malformed);
    REQUIRE(result.fs_result == FilesystemResult::OK);
  }

  SECTION("M return Malformed W file is truncated") {
    // Given a variety of files that abruptly end at various points midway through the
    // data for a valid crash context file
    auto file_size = GENERATE(
        as<size_t>(),
        1,
        5,
        64,
        // Omit the last 8 bytes (footer) or last 1 byte to ensure we detect truncation
        // at different depths
        sizeof(uint64_t) * 2  // valid header magic + version only
    );
    REQUIRE(file_size < data.size());
    const std::string_view truncated_data{data.data(), file_size};
    fs.Touch("crash.ctx", truncated_data);

    // And an open handle to that file
    const bool hold_advisory_lock = false;
    auto open_res = fs.Wrapper().OpenForRead("crash.ctx", hold_advisory_lock);
    REQUIRE(open_res.value == FilesystemResult::OK);

    // When we parse that file as crash context
    auto result = ReadCrashContext(open_res.file);

    // Then we get no value
    REQUIRE(!result.data.has_value());
    REQUIRE(result.GetStatus() == ReadCrashContextResult::Status::Malformed);
    REQUIRE(result.fs_result == FilesystemResult::OK);
  }

  SECTION("M return ReadError W file can not be read due to filesystem error") {
    // Given a file that contains our valid crash context data, but that the filesystem
    // will prevent us from reading
    fs.Touch("crash.ctx", data);
    fs.SimulateFailure(
        "crash.ctx",
        FilesystemResult::PermissionDenied,
        MockFilesystem::FailureFlags::IO
    );

    // And an open handle to that file
    const bool hold_advisory_lock = false;
    auto open_res = fs.Wrapper().OpenForRead("crash.ctx", hold_advisory_lock);
    REQUIRE(open_res.value == FilesystemResult::OK);

    // When we parse that file as a crash report
    auto result = ReadCrashContext(open_res.file);

    // Then we get a result that indicates the filesystem error and contains no data
    REQUIRE(result.GetStatus() == ReadCrashContextResult::Status::ReadError);
    REQUIRE(!result.data.has_value());
    REQUIRE(result.fs_result == FilesystemResult::PermissionDenied);
  }
}
