#pragma once

#include <string_view>

/**
 * A block of data representing some payload generated by a feature.
 * 
 * From the perspective of the Core, a Block is simply a contiguous span of bytes: the
 * format of a given feature's blocks is an implementation detail of that feature. We
 * use `std::string_view` in lieu of C++20's `std::span<uint8_t>`; but the Core should
 * never peek at a block or assume that it represents textual data.
 * 
 * Block is a lightweight, read-only wrapper that does not own the underlying data.
 * Blocks must be copied to std::vector<uint8_t> for durable storage/ownership, e.g.
 * when being passed between threads.
 */
using Block = std::string_view;
