#pragma once

#include <cinttypes>
#include <string>
#include <functional>
#include <memory>

#include "platform/filesystem.hpp"
#include "platform/http.hpp"
#include "core/feature_id.hpp"
#include "core/context.hpp"

/**
 * SCRATCH
 * 
 * Feature registers itself with the core, providing id, name, and:
 * 
 * - a function that will generate reports at the behest of the core, given a context
 *   and a batch of data read from disk
 * 
 * In exchange, the core gives the feature:
 * 
 * - an interface for writing data to storage
 * 
 * When a feature generates a new Block, the Block is passed to a background thread to
 * be immediately serialized to persistent storage (i.e. flushed to disk) in TLV format.
 * Multiple blocks are stored together in batches: each batch is a file. When a batch is
 * ready for upload, it is passed to the feature's report-generation implementation,
 * which reads each Block from the file and generates an HTTP request body that encodes
 * the data represented by the batch.
 */

namespace datadog::impl {

/**
 * A block of data representing some payload generated by a feature.
 * 
 * From the perspective of the Core, a Block is simply a contiguous span of bytes: the
 * format of a given feature's Blocks is an implementation detail of that feature. We
 * use `std::string_view` in lieu of C++20's `std::span<uint8_t>`; but the Core should
 * never assume that a Block represents textual data.
 */
using Block = std::string_view;

/**
 * Interface used by feature implementations in order to write event data to the latest
 * batch in that feature's storage directory.
 */
class StorageWriter
{
private:
    FeatureId _feature_id;

public:
    StorageWriter(FeatureId feature_id);

    /**
     * Queues a feature-specific payload to be written to a TLV file. event must be
     * specified, and it will be written to the latest batch as a block with the 'Event'
     * type. If event_metadata is provided, it will be serialized as a block of type
     * 'Metadata', immediately following the 'Event' block.
     * 
     * @param event A span of bytes representing the payload of the event. This
     *  typically represents the data that should be sent to Datadog intake when this
     *  event is eventually reported.
     * @param event_metadata An optional span of bytes representing an arbitrary set of
     *  data describing the event. This is typically used to inform additional logic
     *  used by the feature when preparing the batch for upload, but it does not
     *  typically encode data that's sent in the resulting HTTP request.
     */
    void EnqueueEventForWrite(Block event, Block event_metadata = {});
};

class IBatchReader
{
};

class Report
{
    std::string_view url;
    std::string_view headers;
    platform::HttpBodyWriter body_writer;
};

struct Feature
{
    FeatureId id;
    std::string name;
    std::unique_ptr<platform::IDirectory> directory;

    Feature(
        FeatureId in_id,
        std::string_view in_name, 
        std::unique_ptr<platform::IDirectory>&& in_directory
    )
        : id(in_id)
        , name(in_name)
        , directory(std::move(in_directory))
    {
    }
};

}
