#pragma once

#include <cinttypes>
#include <string>
#include <functional>
#include <memory>

#include "platform/filesystem.hpp"
#include "platform/http.hpp"
#include "core/context.hpp"

/**
 * SCRATCH
 * 
 * Feature registers itself with the core, providing id, name, and:
 * 
 * - a function that will generate reports at the behest of the core, given a context
 *   and a batch of data read from disk
 * 
 * In exchange, the core gives the feature:
 * 
 * - an interface for writing data to storage
 * 
 * When a feature generates a new Block, the Block is passed to a background thread to
 * be immediately serialized to persistent storage (i.e. flushed to disk) in TLV format.
 * Multiple blocks are stored together in batches: each batch is a file. When a batch is
 * ready for upload, it is passed to the feature's report-generation implementation,
 * which reads each Block from the file and generates an HTTP request body that encodes
 * the data represented by the batch.
 */

namespace datadog::impl {

using FeatureId = uint32_t;

constexpr FeatureId CreateFeatureId(const char fourcc[5])
{
    const uint32_t a = static_cast<uint32_t>(fourcc[0]) << 0;
    const uint32_t b = static_cast<uint32_t>(fourcc[1]) << 8;
    const uint32_t c = static_cast<uint32_t>(fourcc[2]) << 16;
    const uint32_t d = static_cast<uint32_t>(fourcc[3]) << 24;
    return a | b | c | d;
}

/**
 * A block of data representing some payload generated by a feature.
 * 
 * From the perspective of the Core, a Block is simply a contiguous span of bytes: the
 * format of a given feature's Blocks is an implementation detail of that feature. We
 * use `std::string_view` in lieu of C++20's `std::span<uint8_t>`; but the Core should
 * never assume that a Block represents textual data.
 */
using Block = std::string_view;

/**
 * Callback that a feature implementation uses to enqueue a feature-specific event
 * payload to be written to a TLV file. event must be specified, and it will be written
 * to the latest batch as a block with the 'Event' type. If event_metadata is provided,
 * it will be serialized as a block of type 'Metadata', immediately following the
 * 'Event' block.
 * 
 * @param event A span of bytes representing the payload of the event. This
 *  typically represents the data that should be sent to Datadog intake when this
 *  event is eventually reported.
 * @param event_metadata An optional span of bytes representing an arbitrary set of
 *  data describing the event. This is typically used to inform additional logic
 *  used by the feature when preparing the batch for upload, but it does not
 *  typically encode data that's sent in the resulting HTTP request.
 */
using StorageWriter = std::function<bool(Block event, Block event_metadata)>;

class FeatureBase
{
public:
    virtual ~FeatureBase() = default;
    
    virtual FeatureId GetId() const = 0;
    virtual std::string_view GetName() const = 0;

    void OnCoreStarted(StorageWriter writer);
    void OnCoreStopping();

protected:
    virtual void Start() {}
    virtual void Stop() {}

    bool WriteEvent(Block event, Block event_metadata = {});
    bool IsRunning() const;

private:
    StorageWriter _writer;
};

class Report
{
    std::string_view url;
    std::string_view headers;
    platform::HttpBodyWriter body_writer;
};

}
