#pragma once

#include <string_view>
#include <functional>
#include <vector>

#include "core/feature.hpp"
#include "core/queue.hpp"

namespace datadog::impl {

/**
 * A block of data representing some payload generated by a feature.
 * 
 * From the perspective of the Core, a Block is simply a contiguous span of bytes: the
 * format of a given feature's Blocks is an implementation detail of that feature. We
 * use `std::string_view` in lieu of C++20's `std::span<uint8_t>`; but the Core should
 * never assume that a Block represents textual data.
 */
using Block = std::string_view;

/**
 * Message representing an event that needs to be flushed to persistent storage.
 * Produced by a feature implementation in the main thread; handled in the storage
 * thread.
 */
struct StorageWriteMessage
{
    /**
     * Unique FourCC identifier of the feature that produced this message. The
     * accompanying event data will be written in the storage directory for this
     * feature.
     */
    FeatureId feature_id;
    /**
     * 
     */
    Block event;
    Block event_metadata;
};

void StorageThreadMain(Queue<StorageWriteMessage>& queue, std::vector<struct Feature>& features);

}
