stages:
  - build-toolchain-images
#temp#  - validate
#temp#  - build
  - integration
#temp#  - package
#temp#  - release

variables:
  # We must explicitly specify `--parallel <jobs>` when building targets that invoke C++
  # compiles - otherwise, Ninja will run with `-n 41` by default, since it's looking at
  # nproc and not at the actual resource constraints of the Kubernetes pod.
  NUM_PARALLEL_BUILD_JOBS: "8"

  # By default, resource allocation for Datadog CI runners is 1 vCPU and 2 GB RAM. In
  # template-heavy TUs, clang-tidy can reach a maximum resident set size in the ballpark
  # of 512 MB, +/- 100 MB, so 1GB per CPU gives us a reasonable safety margin.
  KUBERNETES_CPU_REQUEST: "8"
  KUBERNETES_CPU_LIMIT: "8"
  KUBERNETES_MEMORY_REQUEST: "8Gi"
  KUBERNETES_MEMORY_LIMIT: "8Gi"

  # Docker registries: we push to registry.ddbuild.io and it replicates to ECR, which
  # Linux runners have access to
  DISTRIBUTION_REGISTRY: registry.ddbuild.io
  BUILD_STABLE_REGISTRY: 486234852809.dkr.ecr.us-east-1.amazonaws.com

  # In order to build Linux toolchain images in CI, we use Docker-in-Docker: this is the
  # image that lets us run Docker builds for that job
  DIND_IMAGE: images/docker:24.0.4-jammy  # Based on a Golden Base Image (GBI) 

  # Our Linux toolchain images are tagged with this version, e.g.
  # 'ci/dd-sdk-cpp:clang15-v2': bump and trigger the job to rebuild
  TOOLCHAIN_IMAGE_PATH: ci/dd-sdk-cpp
  LINUX_TOOLCHAIN_IMAGE_VERSION: v6-b

  # The Windows (MSVC) toolchain image is built separately: since Windows images tend to
  # be large, they are also tagged '<toolchain>-latest' on push, and then the AMI build
  # in `ci-platform-machine-images` pre-pulls the image using that tag. If you bump this
  # version, your Windows CI builds may be slower until the next time Windows runner
  # AMIs are rebuilt.
  WINDOWS_TOOLCHAIN_IMAGE_VERSION: v3-b

  # clang-20 is our golden-path toolchain for development: use the clang-20 image to
  # validate builds with full linting, format checks, etc.
  GOLDEN_LINUX_TOOLCHAIN_TARGET: clang20
  GOLDEN_LINUX_IMAGE: ${BUILD_STABLE_REGISTRY}/${TOOLCHAIN_IMAGE_PATH}:${GOLDEN_LINUX_TOOLCHAIN_TARGET}-${LINUX_TOOLCHAIN_IMAGE_VERSION}

# Stage 'build-toolchain-images' is triggered manually whenever we need to build new
# Docker images for use in later stages of the pipeline to run Linux and Windows builds.
# A Linux toolchain image has CMake, Ninja, and a specific version of GCC or Clang.
# A Windows toolchain image has CMake and a specific version of Visual Studio + MSVC.
# macOS runners use a specific dd-sdk-cpp-sonoma AMI in lieu of Docker.

build-toolchain-image-linux:
  stage: build-toolchain-images
  when: manual
  except: [tags, schedules]
  tags: [arch:amd64]
  image: ${BUILD_STABLE_REGISTRY}/${DIND_IMAGE}
  parallel:
    matrix:
      - TOOLCHAIN_TARGET: [gcc11, gcc13, clang15, clang20]
  script:
    - export TOOLCHAIN_IMAGE="${DISTRIBUTION_REGISTRY}/${TOOLCHAIN_IMAGE_PATH}:${TOOLCHAIN_TARGET}-${LINUX_TOOLCHAIN_IMAGE_VERSION}"
    - docker buildx build --target ${TOOLCHAIN_TARGET} --tag ${TOOLCHAIN_IMAGE} --label target=build --push ./ci/linux

build-toolchain-image-windows:
  stage: build-toolchain-images
  when: manual
  except: [tags, schedules]
  tags: [windows-v2:2022]
  id_tokens:
    CI_IDENTITY_GITLAB_JWT:
      aud: https://vault.us1.ddbuild.io  # Required for docker push
  variables:
    CI_IDENTITY_ROLE_NAME_OVERRIDE: windows-ci-tmp-gitlab-id-token-dd-sdk-cpp-all-refs  # Required for docker push
    OVERRIDE_GIT_STRATEGY: clone  # Required for Windows runners
    TOOLCHAIN_TARGET: vs2022  # Visual Studio 2022 17.14; MSVC v143
  # Build a Docker image, then tag it as both (e.g.) 'vs2022-v1' and 'vs2022-latest':
  # the latter tag is used to cache the latest image locally when building Windows
  # runner AMIs (see `pre-pull-docker-images.ps1` in ci-platform-machine-images)
  script:
    - $ErrorActionPreference = "Stop"
    - $env:TOOLCHAIN_IMAGE = "${env:DISTRIBUTION_REGISTRY}/${env:TOOLCHAIN_IMAGE_PATH}:${env:TOOLCHAIN_TARGET}-${env:WINDOWS_TOOLCHAIN_IMAGE_VERSION}"
    - $env:TOOLCHAIN_IMAGE_LATEST = "${env:DISTRIBUTION_REGISTRY}/${env:TOOLCHAIN_IMAGE_PATH}:${env:TOOLCHAIN_TARGET}-latest"
    - docker build --tag ${env:TOOLCHAIN_IMAGE} --label target=build ./ci/windows
    - If ($LASTEXITCODE -ne "0") { throw "docker build returned $LASTEXITCODE" }
    - docker tag ${env:TOOLCHAIN_IMAGE} ${env:TOOLCHAIN_IMAGE_LATEST}
    - If ($LASTEXITCODE -ne "0") { throw "docker tag returned $LASTEXITCODE" }
    - docker push ${env:TOOLCHAIN_IMAGE}
    - If ($LASTEXITCODE -ne "0") { throw "docker push returned $LASTEXITCODE" }
    - docker push ${env:TOOLCHAIN_IMAGE_LATEST}
    - If ($LASTEXITCODE -ne "0") { throw "docker push returned $LASTEXITCODE" }

# Stage 'validate' performs quick up-front validation, using clang-20 with full support
# for clang-format and clang-tidy

#temp#check-format:
#temp#  stage: validate
#temp#  tags: [arch:amd64]
#temp#  image: ${GOLDEN_LINUX_IMAGE}
#temp#  script:
#temp#    - cmake -DDD_ENABLE_CLANG_FORMAT=ON -S . -B build
#temp#    - cmake --build build --target check-format
#temp#
#temp#validate-event-types:
#temp#  stage: validate
#temp#  tags: [arch:amd64]
#temp#  image: ${GOLDEN_LINUX_IMAGE}
#temp#  script:
#temp#    - cmake -DDD_ENABLE_EVENT_VALIDATION=ON -S . -B build
#temp#    - cmake --build build --target validate-event-types
#temp#
#temp#unit-test:
#temp#  stage: validate
#temp#  tags: [arch:amd64]
#temp#  image: ${GOLDEN_LINUX_IMAGE}
#temp#  parallel:
#temp#    matrix:
#temp#      - BUILD_CONFIGURATION: [Debug, RelWithDebInfo]
#temp#  script:
#temp#    - >
#temp#      cmake
#temp#      -DCMAKE_BUILD_TYPE=${BUILD_CONFIGURATION}
#temp#      -DDD_ENABLE_ASSERTS=ON
#temp#      -DDD_ENABLE_CLANG_TIDY=ON
#temp#      -DDD_BUILD_EXAMPLES=ON
#temp#      -DDD_BUILD_TESTING=ON
#temp#      -S . -B build
#temp#    - cmake --build build --parallel ${NUM_PARALLEL_BUILD_JOBS}
#temp#    - ctest --test-dir build --output-on-failure --output-junit test-results/test-results.xml
#temp#  artifacts:
#temp#    when: always
#temp#    expire_in: "30 days"
#temp#    reports:
#temp#      junit: ${CI_PROJECT_DIR}/build/test-results/*.xml

# Stage 'build' performs a more exhaustive set of library builds to validate that our
# library builds successfully on all supported compilers in all configurations.

#temp#build-linux:
#temp#  stage: build
#temp#  dependencies: []
#temp#  tags: [arch:amd64]
#temp#  parallel:
#temp#    # To avoid ballooning our build matrix, test multiple variations (compiler version,
#temp#    # static vs. shared, release vs. debug, etc.) in each job. clang20 builds all
#temp#    # targets in the unit-test job, so we don't need to exercise it here.
#temp#    matrix:
#temp#      # gcc11: shared-debug, w/ runtime dependency on libcurl.so
#temp#      - TOOLCHAIN_TARGET: gcc11
#temp#        BUILD_CONFIGURATION: Debug
#temp#        BUILD_SHARED_LIBS: "ON"
#temp#        USE_SYSTEM_LIBCURL: "ON"
#temp#
#temp#      # gcc13: static-release, w/ bundled libcurl
#temp#      - TOOLCHAIN_TARGET: gcc13
#temp#        BUILD_CONFIGURATION: Release
#temp#        BUILD_SHARED_LIBS: "OFF"
#temp#        USE_SYSTEM_LIBCURL: "OFF"
#temp#
#temp#      # clang15: static-release, w/ runtime dependency on libcurl.so
#temp#      - TOOLCHAIN_TARGET: clang15
#temp#        BUILD_CONFIGURATION: Release
#temp#        BUILD_SHARED_LIBS: "OFF"
#temp#        USE_SYSTEM_LIBCURL: "ON"
#temp#
#temp#      # clang15: shared-debug, w/ bundled libcurl
#temp#      - TOOLCHAIN_TARGET: clang15
#temp#        BUILD_CONFIGURATION: Debug
#temp#        BUILD_SHARED_LIBS: "ON"
#temp#        USE_SYSTEM_LIBCURL: "OFF"
#temp#
#temp#  image: ${BUILD_STABLE_REGISTRY}/${TOOLCHAIN_IMAGE_PATH}:${TOOLCHAIN_TARGET}-${LINUX_TOOLCHAIN_IMAGE_VERSION}
#temp#  script:
#temp#    - >
#temp#      cmake
#temp#      -DCMAKE_BUILD_TYPE=${BUILD_CONFIGURATION}
#temp#      -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
#temp#      -DDD_HTTP_USE_SYSTEM_LIBCURL=${USE_SYSTEM_LIBCURL}
#temp#      -S . -B build
#temp#    - cmake --build build --parallel ${NUM_PARALLEL_BUILD_JOBS}
#temp#
#temp#build-macos:
#temp#  stage: build
#temp#  dependencies: []
#temp#  tags: [macos:sonoma, specific:true] # Use AMI dd-sdk-cpp-sonoma, w/ Xcode 15.3.0, AppleClang 15
#temp#  parallel:
#temp#    # Ensure that all targets build on macOS
#temp#    matrix:
#temp#      # clang15 (Apple): shared-debug, w/ runtime dependency on libcurl.so
#temp#      - BUILD_CONFIGURATION: Debug
#temp#        BUILD_SHARED_LIBS: "ON"
#temp#        USE_SYSTEM_LIBCURL: "ON"
#temp#
#temp#      # clang15 (Apple): static-release, w/ bundled libcurl
#temp#      - BUILD_CONFIGURATION: Release
#temp#        BUILD_SHARED_LIBS: "OFF"
#temp#        USE_SYSTEM_LIBCURL: "OFF"
#temp#  script:
#temp#    - >
#temp#      cmake
#temp#      -DCMAKE_BUILD_TYPE=${BUILD_CONFIGURATION}
#temp#      -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
#temp#      -DDD_HTTP_USE_SYSTEM_LIBCURL=${USE_SYSTEM_LIBCURL}
#temp#      -S . -B build
#temp#    - cmake --build build --parallel ${NUM_PARALLEL_BUILD_JOBS}
#temp#
#temp#build-windows:
#temp#  stage: build
#temp#  dependencies: []
#temp#  tags: [windows-v2:2022]
#temp#  variables:
#temp#    OVERRIDE_GIT_STRATEGY: clone  # Required for Windows runners
#temp#    TOOLCHAIN_TARGET: vs2022
#temp#  parallel:
#temp#    matrix:
#temp#      # Visual Studio 2022 (17.14, vc143): md-static-debug, w/ bundled libcurl
#temp#      - BUILD_CONFIGURATION: Release
#temp#        BUILD_SHARED_LIBS: "OFF"
#temp#        USE_SYSTEM_LIBCURL: "OFF"
#temp#        MSVC_RUNTIME_LIBRARY: MultiThreadedDebugDLL
#temp#  script:
#temp#    - $ErrorActionPreference = "Stop"
#temp#    - if (Test-Path build) { remove-item -recurse -force build }
#temp#    - $env:TOOLCHAIN_IMAGE = "${env:DISTRIBUTION_REGISTRY}/${env:TOOLCHAIN_IMAGE_PATH}:${env:TOOLCHAIN_TARGET}-${env:WINDOWS_TOOLCHAIN_IMAGE_VERSION}"
#temp#    - >
#temp#      docker run --rm
#temp#      -m 8192M
#temp#      -v "$(Get-Location):C:\mnt"
#temp#      -w C:\mnt
#temp#      ${env:TOOLCHAIN_IMAGE}
#temp#      cmd /S /C "cmake -DCMAKE_BUILD_TYPE=${env:BUILD_CONFIGURATION} -DBUILD_SHARED_LIBS=${env:BUILD_SHARED_LIBS} -DDD_HTTP_USE_SYSTEM_LIBCURL=${env:USE_SYSTEM_LIBCURL} -DMSVC_RUNTIME_LIBRARY=${env:MSVC_RUNTIME_LIBRARY} -S . -B build && cmake --build build --config ${env:BUILD_CONFIGURATION} --parallel ${env:NUM_PARALLEL_BUILD_JOBS}"
#temp#    - If ($LASTEXITCODE -ne "0") { throw "docker run (cmake build) returned $LASTEXITCODE" }

# Stage 'integration' runs integration tests on all supported platforms

# TEMP: For now, just verify that we have the vault CLI installed on all platforms, and
# examine basic vault state

integration-test-linux:
  stage: integration
  dependencies: []
  tags: [arch:amd64]
  image: ${GOLDEN_LINUX_IMAGE}
  script:
    - echo "CI is $CI"
    - echo "CI_RUNNER_TAGS is $CI_RUNNER_TAGS"
    - echo "KUBERNETES_SERVICE_HOST is $KUBERNETES_SERVICE_HOST"
    - echo "VAULT_ADDR is $VAULT_ADDR"
    - vault --version
    - vault status
    - vault token lookup || echo 'no vault token'

integration-test-macos:
  stage: integration
  dependencies: []
  tags: [macos:sonoma, specific:true] # Use AMI dd-sdk-cpp-sonoma, w/ Xcode 15.3.0, AppleClang 15
  script:
    - echo "CI is $CI"
    - echo "CI_RUNNER_TAGS is $CI_RUNNER_TAGS"
    - echo "KUBERNETES_SERVICE_HOST is $KUBERNETES_SERVICE_HOST"
    - echo "VAULT_ADDR is $VAULT_ADDR"
    - vault --version
    - vault status
    - vault login -method=aws -no-print  # macOS runners must obtain a Vault token using AWS IAM authentication
    - vault token lookup || echo 'no vault token'

integration-test-windows:
  stage: integration
  dependencies: []
  tags: [windows-v2:2022]
  id_tokens:
    CI_IDENTITIES_GITLAB_ID_TOKEN:
      aud: ci-identities
  variables:
    CI_IDENTITIES_CLIENT_VERSION: v0.1.0
    OVERRIDE_GIT_STRATEGY: clone  # Required for Windows runners
    TOOLCHAIN_TARGET: vs2022
  script:
    - $ErrorActionPreference = "Stop"
    - aws s3 cp "s3://binaries-ddbuild-io-prod/ci-identities/ci-identities-gitlab-job-client/versions/${env:CI_IDENTITIES_CLIENT_VERSION}/ci-identities-gitlab-job-client-windows-amd64.exe" ./ci-identities-gitlab-job-client.exe
    - .\ci-identities-gitlab-job-client.exe assume-role

# Stage 'package' generates release artifacts for the toolchains/configurations that we
# support with precompiled binaries

#temp#package-linux:
#temp#  stage: package
#temp#  dependencies: []
#temp#  tags: [arch:amd64]
#temp#  parallel:
#temp#    matrix:
#temp#      # linux-{arch}-clang-libstdc++-shared-release
#temp#      - TOOLCHAIN_TARGET: clang20
#temp#        BUILD_CONFIGURATION: RelWithDebInfo
#temp#        BUILD_SHARED_LIBS: "ON"
#temp#  image: ${BUILD_STABLE_REGISTRY}/${TOOLCHAIN_IMAGE_PATH}:${TOOLCHAIN_TARGET}-${LINUX_TOOLCHAIN_IMAGE_VERSION}
#temp#  script:
#temp#    - cmake -DCMAKE_BUILD_TYPE=${BUILD_CONFIGURATION} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} -S . -B build
#temp#    - cmake --build build --target package --parallel ${NUM_PARALLEL_BUILD_JOBS}
#temp#    - stat build/artifact_name.txt
#temp#    - stat "build/$(cat build/artifact_name.txt).tar.gz"
#temp#  artifacts:
#temp#    expire_in: "1 week"
#temp#    paths:
#temp#      - build/ddsdkcpp-*.tar.gz
#temp#
#temp#package-macos:
#temp#  stage: package
#temp#  dependencies: []
#temp#  tags: [macos:sonoma, specific:true] # Use AMI dd-sdk-cpp-sonoma, w/ Xcode 15.3.0, AppleClang 15
#temp#  parallel:
#temp#    matrix:
#temp#      # macos-{arch}-clang-libc++-shared-release
#temp#      - BUILD_CONFIGURATION: RelWithDebInfo
#temp#        BUILD_SHARED_LIBS: "ON"
#temp#  script:
#temp#    - cmake -DCMAKE_BUILD_TYPE=${BUILD_CONFIGURATION} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} -S . -B build
#temp#    - cmake --build build --target package --parallel ${NUM_PARALLEL_BUILD_JOBS}
#temp#    - stat build/artifact_name.txt
#temp#    - stat "build/$(cat build/artifact_name.txt).tar.gz"
#temp#  artifacts:
#temp#    expire_in: "1 week"
#temp#    paths:
#temp#      - build/ddsdkcpp-*.tar.gz
#temp#
#temp#package-windows:
#temp#  stage: package
#temp#  dependencies: []
#temp#  tags: [windows-v2:2022]
#temp#  variables:
#temp#    OVERRIDE_GIT_STRATEGY: clone  # Required for Windows runners
#temp#    TOOLCHAIN_TARGET: vs2022
#temp#  parallel:
#temp#    matrix:
#temp#      # windows-x64-msvc143-md-shared-release
#temp#      - BUILD_CONFIGURATION: RelWithDebInfo
#temp#        BUILD_SHARED_LIBS: "ON"
#temp#        USE_SYSTEM_LIBCURL: "OFF"  # Build static libcurl from source
#temp#        MSVC_RUNTIME_LIBRARY: MultiThreadedDLL
#temp#  script:
#temp#    - $ErrorActionPreference = "Stop"
#temp#    - if (Test-Path build) { remove-item -recurse -force build }
#temp#    - $env:TOOLCHAIN_IMAGE = "${env:DISTRIBUTION_REGISTRY}/${env:TOOLCHAIN_IMAGE_PATH}:${env:TOOLCHAIN_TARGET}-${env:WINDOWS_TOOLCHAIN_IMAGE_VERSION}"
#temp#    - >
#temp#      docker run --rm
#temp#      -m 8192M
#temp#      -v "$(Get-Location):C:\mnt"
#temp#      -w C:\mnt
#temp#      ${env:TOOLCHAIN_IMAGE}
#temp#      cmd /S /C "cmake -DCMAKE_BUILD_TYPE=${env:BUILD_CONFIGURATION} -DBUILD_SHARED_LIBS=${env:BUILD_SHARED_LIBS} -DDD_HTTP_USE_SYSTEM_LIBCURL=${env:USE_SYSTEM_LIBCURL} -DMSVC_RUNTIME_LIBRARY=${env:MSVC_RUNTIME_LIBRARY} -S . -B build && cmake --build build --config ${env:BUILD_CONFIGURATION} --target package --parallel ${env:NUM_PARALLEL_BUILD_JOBS}"
#temp#    - If ($LASTEXITCODE -ne "0") { throw "docker run (cmake build) returned $LASTEXITCODE" }
#temp#  artifacts:
#temp#    expire_in: 1 week
#temp#    paths:
#temp#      - build/ddsdkcpp-*.zip

# Stage 'release' gathers all the artifacts from the 'package' stage and... prints their
# names.

#temp#create-release:
#temp#  stage: release
#temp#  rules:
#temp#    - if: '$CI_COMMIT_BRANCH == "main"'
#temp#      changes: [CMakeLists.txt]  # Contains canonical project version number
#temp#    - when: never
#temp#  dependencies:
#temp#    - package-linux
#temp#    - package-macos
#temp#    - package-windows
#temp#  tags: [arch:amd64]
#temp#  image: ${GOLDEN_LINUX_IMAGE}
#temp#  script:
#temp#    # TODO: Verify whether release actually needs to happen; get GitHub App Token;
#temp#    # create draft release; upload artifacts
#temp#    - RELEASE_VERSION=$(grep -E '^project\(ddsdkcpp VERSION ([0-9]+\.[0-9]+\.[0-9]+[^ ]*)' CMakeLists.txt | cut -d' ' -f3)
#temp#    - |
#temp#      if [ "$RELEASE_VERSION" == "" ]; then
#temp#        echo "ERROR: Failed to parse version from CMakeLists.txt" >&2
#temp#        exit 1
#temp#      fi
#temp#    - ARCHIVE_FILES=$(find build -maxdepth 1 -type f \( -name 'ddsdkcpp-*.tar.gz' -o -name 'ddsdkcpp-*.zip' \))
#temp#    - |
#temp#      if [ "$ARCHIVE_FILES" == "" ]; then
#temp#        echo "ERROR: No archive files found in previous jobs' artifacts" >&2
#temp#        exit 1
#temp#      fi
#temp#    - |
#temp#      echo "Preparing release of dd-sdk-cpp $RELEASE_VERSION."
#temp#      echo "Artifacts found:"
#temp#      for ARCHIVE_PATH in $ARCHIVE_FILES; do
#temp#        ARCHIVE_FILENAME=$(basename "$ARCHIVE_PATH")
#temp#        echo "- $ARCHIVE_FILENAME"
#temp#      done
