FROM registry.ddbuild.io/images/docker:24.0.4-gbi-focal

ENV DEBIAN_FRONTEND=noninteractive

# Set timezone to UTC by default
RUN ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime

RUN apt-get -y install ca-certificates gpg wget

# LLVM - Focal doesn't have clang 15, to get it directly from LLVM
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN echo 'deb https://apt.llvm.org/focal/ llvm-toolchain-focal-15 main' | tee -a /etc/apt/sources.list.d/llvm.list >/dev/null \
  && apt-get update \
  && apt-get -y install clang-15 clang-format-15 clang-tidy-15 clang-tools-15
RUN apt-get update \
  && apt-get -y install libc++-dev libc++1 libc++abi-dev libc++abi1

# CMake - use kitware repo for most updated version
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal-rc main' | tee -a /etc/apt/sources.list.d/kitware.list >/dev/null \
  && apt-get update \
  && apt-get -y install cmake
