# Unless explicitly stated otherwise all files in this repository are licensed under the
# Apache License Version 2.0.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025-Present Datadog, Inc.
import os
import sys
import platform
import re
import uuid

from lib.test import TestContext


async def main(t: TestContext):
    """
    CrashReporting: smoke test
    """
    # Given an initial SDK process, with both RUM and crash reporting enabled
    # When that process establishes some RUM state and then experiences a crash
    p1 = t.spawn_repl()
    p1.run("""
    set-config client-token fake-client-token
    set-config rum-application-id a991ca10-4004-4004-4004-beefbeefbeef
    create-core tracking-consent:granted
    register-crash-reporting
    register-rum
    start-core
    set-account-info acct-456 name:"Bits"
    start-view foo
    sleep 10
    crash bad-sdk-usage
    """)
    await p1.join()
    assert p1.exitcode != 0

    # Then no uploads were initiated by that process
    assert len(p1.requests) == 0

    # And our RUM view event remains on disk
    p1_rum_events_dir = t.storage.get_granted_events_dir(p1.pid, 'rum')
    assert p1_rum_events_dir.is_dir()
    event_filenames = os.listdir(p1_rum_events_dir)
    assert len(event_filenames) == 1

    # And our .crashes/ directory contains a crash file as well as a crash context file
    crashes_dir = t.storage.get_artifact_dir('.crashes')
    assert crashes_dir.is_dir()
    p1_crash_filenames = sorted(os.listdir(crashes_dir))
    assert len(p1_crash_filenames) == 2
    assert p1_crash_filenames[0].startswith('crash_')
    assert p1_crash_filenames[0].endswith(f'_{p1.pid}')
    assert p1_crash_filenames[1] == p1_crash_filenames[0] + '.ctx'
    p1_crash_filename, p1_context_filename = p1_crash_filenames

    # And both files are non-empty
    p1_crash_file_path = crashes_dir / p1_crash_filename
    p1_context_file_path = crashes_dir / p1_context_filename
    assert os.stat(p1_crash_file_path).st_size > 0
    assert os.stat(p1_context_file_path).st_size > 0

    # Next: When we start another process with the same configuration, configured to
    # flush requests on shutdown
    p2 = t.spawn_repl()
    p2.run("""
    set-config client-token fake-client-token
    set-config rum-application-id a991ca10-4004-4004-4004-beefbeefbeef
    set-config flush-on-stop
    create-core tracking-consent:granted
    register-crash-reporting
    register-rum
    start-core
    sleep 10
    stop-core
    exit
    """)
    await p2.join()
    assert p2.exitcode == 0

    # Then our original process's RUM events dir no longer exists because the new
    # process took ownership of that leftover data
    assert not p1_rum_events_dir.exists()

    # And both of our crash files have been deleted
    assert not p1_crash_file_path.exists()
    assert not p1_context_file_path.exists()

    # And the new process uploaded two batches of RUM data (one inherited from p1,
    # another created fresh in p2)
    assert len(p2.requests) == 2
    assert p2.requests[0].method == 'POST'
    assert p2.requests[0].url.path == '/api/v2/rum'
    assert p2.requests[1].method == 'POST'
    assert p2.requests[1].url.path == '/api/v2/rum'

    # And the first batch includes the original RUM View event generated by p1
    p1_rum_events = p2.requests[0].json
    assert len(p1_rum_events) == 1
    assert p1_rum_events[0]['type'] == 'view'
    p1_view = p1_rum_events[0]
    assert p1_view['application']['id'] == 'a991ca10-4004-4004-4004-beefbeefbeef'
    assert p1_view['account']['id'] == 'acct-456'
    assert p1_view['account']['name'] == 'Bits'
    assert p1_view['view']['is_active'] == True
    assert p1_view['view']['error']['count'] == 0
    assert 'crash' not in p1_view['view']

    # And the second batch includes both an updated RUM View event and a RUM Error event
    p2_rum_events = p2.requests[1].json
    assert len(p2_rum_events) == 2
    assert p2_rum_events[0]['type'] == 'view'
    assert p2_rum_events[1]['type'] == 'error'
    p2_view, p2_error = p2_rum_events

    # And the later view event describes the same view that was recorded in the original
    # process, but with is_active False, error/crash counts incremented, and a modified
    # date value
    assert p2_view['account'] == p1_view['account']
    assert p2_view['application']['id'] == p1_view['application']['id']
    assert p2_view['session']['id'] == p1_view['session']['id']
    assert p2_view['view']['id'] == p1_view['view']['id']
    assert p2_view['view']['is_active'] == False
    assert p2_view['view']['error']['count'] == 1
    assert p2_view['view']['crash']['count'] == 1
    assert p2_view['date'] > p1_view['date']

    # And the error event is associated with that view, with its timestamp being just
    # after the newly-recorded end of the view
    assert p2_error['date'] == p2_view['date'] + 1
    assert p2_error['account'] == p1_view['account']
    assert p2_error['application']['id'] == p1_view['application']['id']
    assert p2_error['session']['id'] == p1_view['session']['id']
    assert p2_error['view']['id'] == p1_view['view']['id']

    # And the error contains the basic details of a crash triggered by the repl's
    # 'crash bad-sdk-usage' command
    if sys.platform == 'win32':
        want_message = 'Application crash: EXCEPTION_ACCESS_VIOLATION (0xC0000005)'
        want_source_type = 'windows'
    else:
        want_message = 'Application crash: SIGSEGV (Segmentation fault)'
        want_source_type = 'macos' if sys.platform == 'darwin' else 'linux'
    assert p2_error['error']['message'] == want_message
    assert p2_error['error']['source_type'] == want_source_type
    assert p2_error['error']['source'] == 'source'
    assert p2_error['error']['is_crash'] == True

    # And error contains at least one 'binary_images' entry
    assert len(p2_error['error']['binary_images']) > 0

    # And at least one of those entries describes the program that crashed, which in our
    # case is the SDK's own repl example program
    exe_name = 'dd_native_repl'
    if sys.platform == 'win32':
        exe_name += '.exe'
    repl_image = next((x for x in p2_error['error']['binary_images'] if x['name'] == exe_name), None)
    assert repl_image

    # And the program is not identified as a system library
    assert repl_image['is_system'] == False

    # And the program is described as having the same CPU architecture as this system
    if platform.machine().lower() in ('x64', 'x86_64', 'amd64'):
        want_arch = 'x64'
    elif platform.machine().lower() in ('arm64', 'aarch64'):
        want_arch = 'arm64'
    else:
        assert False, f'unsupported CPU arch {platform.machine()}'
    assert repl_image['arch'] == want_arch

    # And the range of the crashing process's address space where the executable was
    # loaded is denoted, hex-formatted, with sensible values
    exe_load_address = int(repl_image['load_address'], 16)
    exe_max_address = int(repl_image['max_address'], 16)
    assert exe_max_address > exe_load_address
    exe_resident_size = exe_max_address - exe_load_address
    thirty_two_megabytes = 32 * 1024 * 1024
    assert exe_resident_size < thirty_two_megabytes

    # And the binary_images[].uuid value is a sensibly-formatted build ID for this
    # executable on this platform
    build_id = repl_image['uuid']
    assert build_id
    assert isinstance(build_id, str)
    assert len(build_id) < 64
    if sys.platform == 'win32':
        # Win32: PDB GUID (hex) and Age (decimal) from CodeView record
        assert len(build_id) > 32
        pdb_guid, age_str = build_id[:32], build_id[32:]
        assert re.match(r'[0-9A-F]+', pdb_guid)
        age = int(age_str)
        assert age > 0
        assert age < 999
    elif sys.platform == 'darwin':
        # MacOS: UUID from Mach-O header (LC_UUID), parseable as a valid UUID
        assert re.match(r'[0-9a-f\-]+', build_id)
        uid = uuid.UUID(build_id)
        assert uid != uuid.UUID(int=0)
    else:
        # Linux: ELF Build ID from NT_GNU_BUILD_ID, formatted lowercase hex
        assert re.match(r'[0-9a-f]+', build_id)
    
    # And the error.stack value is formatted as a multiline string matching the same
    # regex used to parse stack traces on the backend, where at least one frame refers
    # to instructions from the repl executable, and all such frames place those
    # instructions within the executable's address range
    num_lines_in_exe = 0
    has_seen_empty_line = False
    native_stack_frame_regex = re.compile(r'^([0-9]+)\s+(.+)\s+(0x[0-9a-f]{16}) (0x[0-9a-f]+) \+ ([0-9]+)$')
    for line in p2_error['error']['stack'].splitlines():
        if not line:
            assert not has_seen_empty_line
            has_seen_empty_line = True
            continue
        match = native_stack_frame_regex.match(line)
        assert match
        if match.group(2) == exe_name:
            num_lines_in_exe += 1

            # raw_address should be located within repl exe address range
            assert match.group(3).startswith('0x')
            raw_address = int(match.group(3)[2:], 16)
            assert raw_address >= exe_load_address
            assert raw_address < exe_max_address

            # load_address should match the value from binary_images
            assert match.group(4).startswith('0x')
            load_address = int(match.group(4)[2:], 16)
            assert load_address == exe_load_address

            # Decimal offset should be less than computed resident size of exe
            offset = int(match.group(5))
            assert offset < exe_resident_size
    assert num_lines_in_exe > 0
