# Unless explicitly stated otherwise all files in this repository are licensed under the
# Apache License Version 2.0.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025-Present Datadog, Inc.
import os

from lib.test import TestContext


async def main(t: TestContext):
    """
    CrashReporting: smoke test
    """
    # Given an initial SDK process, with both RUM and crash reporting enabled
    # When that process establishes some RUM state and then experiences a crash
    p1 = t.spawn_repl()
    p1.run("""
    set-config client-token fake-client-token
    set-config rum-application-id a991ca10-4004-4004-4004-beefbeefbeef
    set-config tracking-consent granted
    create-core
    register-crash-reporting
    register-rum
    start-core
    start-view foo
    flush-work
    crash bad-sdk-usage
    """)
    await p1.join()
    assert p1.exitcode != 0

    # Then no uploads were initiated by that process
    assert len(p1.requests) == 0

    # And our RUM view event remains on disk
    p1_rum_events_dir = t.storage.get_granted_events_dir(p1.pid, 'rum')
    assert p1_rum_events_dir.is_dir()
    event_filenames = os.listdir(p1_rum_events_dir)
    assert len(event_filenames) == 1

    # And our .crashes/ directory contains a crash file as well as a crash context file
    crashes_dir = t.storage.get_artifact_dir('.crashes')
    assert crashes_dir.is_dir()
    p1_crash_filenames = sorted(os.listdir(crashes_dir))
    assert len(p1_crash_filenames) == 2
    assert p1_crash_filenames[0].startswith('crash_')
    assert p1_crash_filenames[0].endswith(f'_{p1.pid}')
    assert p1_crash_filenames[1] == p1_crash_filenames[0] + '.ctx'
    p1_crash_filename, p1_context_filename = p1_crash_filenames

    # And both files are non-empty
    p1_crash_file_path = crashes_dir / p1_crash_filename
    p1_context_file_path = crashes_dir / p1_context_filename
    assert os.stat(p1_crash_file_path).st_size > 0
    assert os.stat(p1_context_file_path).st_size > 0

    # Next: When we start another process with the same configuration, configured to
    # flush requests on shutdown
    p2 = t.spawn_repl()
    p2.run("""
    set-config client-token fake-client-token
    set-config rum-application-id a991ca10-4004-4004-4004-beefbeefbeef
    set-config tracking-consent granted
    set-config flush-on-stop
    create-core
    register-crash-reporting
    register-rum
    start-core
    stop-core
    exit
    """)
    await p2.join()
    assert p2.exitcode == 0

    # Then our original process's RUM events dir no longer exists because the new
    # process took ownership of that leftover data
    assert not p1_rum_events_dir.exists()

    # And both of our crash files have been deleted
    assert not p1_crash_file_path.exists()
    assert not p1_context_file_path.exists()

    # And the new process uploaded a batch of RUM data
    assert len(p2.requests) == 1
    assert p2.requests[0].method == 'POST'
    assert p2.requests[0].url.path == '/api/v2/rum'
    rum_events = p2.requests[0].json

    # And that batch includes the original RUM View event generated by p1
    assert len(rum_events) > 0
    assert rum_events[0]['type'] == 'view'
    assert rum_events[0]['application']['id'] == 'a991ca10-4004-4004-4004-beefbeefbeef'
    assert rum_events[0]['view']['is_active'] == True

    # TODO(RUM-15994): Validate that p2 also produces a RUM Error event describing the
    # crash, as well as another RUM View event that increments error/crash counts, sets
    # view.is_active to false, and updates the view duration to encompass the moment of
    # the crash
