#!/usr/bin/env python3
# Unless explicitly stated otherwise all files in this repository are licensed under the
# Apache License Version 2.0.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025-Present Datadog, Inc.
"""
Generate Windows to IANA timezone mapping header file.

This script fetches the CLDR windowsZones.xml file and generates a C++ header
with a static mapping table from Windows timezone names to IANA timezone IDs.

Usage:
    python3 generate-windows-timezone-mapping.py

Output:
    src/datadog/impl/platform/windows_timezone_mapping.hpp
"""
import subprocess
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import List, Tuple

CLDR_URL = "https://raw.githubusercontent.com/unicode-org/cldr/refs/heads/main/common/supplemental/windowsZones.xml"
OUTPUT_FILE = "src/datadog/impl/platform/windows_timezone_mapping.hpp"


def fetch_windows_zones_xml() -> str:
    """Fetch the windowsZones.xml file from CLDR."""
    print(f"Fetching timezone data from {CLDR_URL}...")
    with urllib.request.urlopen(CLDR_URL) as response:
        return response.read().decode('utf-8')


def parse_timezone_mappings(xml_content: str) -> List[Tuple[str, str]]:
    """
    Parse the windowsZones.xml and extract Windows -> IANA mappings.

    Returns a list of (windows_tz, iana_tz) tuples, sorted by Windows timezone name.
    """
    root = ET.fromstring(xml_content)
    mappings = {}

    # Navigate to the mapZone elements
    # Structure: supplementalData > windowsZones > mapTimezones > mapZone
    for map_zone in root.findall('.//mapZone'):
        windows_tz = map_zone.get('other')
        iana_tz = map_zone.get('type')
        territory = map_zone.get('territory')

        # Only use mappings for territory="001" (default/primary mapping)
        if territory == "001" and windows_tz and iana_tz:
            # Some entries have multiple IANA zones (space-separated)
            # We take the first one as the primary mapping
            primary_iana = iana_tz.split()[0]
            mappings[windows_tz] = primary_iana

    # Sort by Windows timezone name for consistent output and binary search
    return sorted(mappings.items())


def generate_header_file(mappings: List[Tuple[str, str]], output_path: Path) -> None:
    """Generate the C++ header file with the timezone mapping table."""
    print(f"Generating {output_path}...")

    # Calculate table size
    table_size = len(mappings)

    header_content = f"""// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
//
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

// Generated by tools/generate-windows-timezone-mapping/main.py - DO NOT EDIT
//
// This file contains a mapping from Windows timezone names to IANA timezone IDs.
// The table is sorted by Windows timezone name to enable binary search. Generated from:
// {CLDR_URL}

#pragma once

#include <cstddef>
#include <string_view>

namespace datadog::platform {{

/**
 * Description of a Windows-specific timezone name and an equivalent IANA timezone name.
 *
 * Strings are guaranteed to be immutable values with static storage.
 */
struct WindowsTimezoneMapping {{
  std::string_view windows_tz;
  std::string_view iana_tz;
}};

static constexpr WindowsTimezoneMapping WINDOWS_TIMEZONE_LOOKUP[] = {{
"""

    # Add each mapping entry
    for windows_tz, iana_tz in mappings:
        # Escape any special characters in strings
        windows_escaped = windows_tz.replace('\\', '\\\\').replace('"', '\\"')
        iana_escaped = iana_tz.replace('\\', '\\\\').replace('"', '\\"')
        header_content += f'  {{"{windows_escaped}", "{iana_escaped}"}},\n'

    header_content += f"""}};\n

std::string_view MapWindowsTimezoneToIANA(std::string_view windows_tz);

}}  // namespace datadog::platform
"""

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write the file
    output_path.write_text(header_content)
    print(f"Successfully generated {output_path} with {table_size} timezone mappings.")


def main():
    """Main entry point."""
    try:
        # Fetch and parse the XML
        xml_content = fetch_windows_zones_xml()
        mappings = parse_timezone_mappings(xml_content)

        if not mappings:
            raise RuntimeError("No timezone mappings found in XML")

        # Generate the header file
        script_dir = Path(__file__).parent
        repo_root = script_dir.parent.parent
        output_path = repo_root / OUTPUT_FILE
        generate_header_file(mappings, output_path)
        print(f"\nGenerated: {output_path}")

        # Invoke clang-format to auto-format our file
        subprocess.check_call(['clang-format', '-i', OUTPUT_FILE], cwd=repo_root)

    except Exception as e:
        print(f"Error: {e}")
        return 1

    return 0


if __name__ == "__main__":
    exit(main())
