// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
//
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

#include "datadog/impl/storage/event.hpp"

#include <charconv>

#include "datadog/impl/assert.hpp"
#include "datadog/impl/storage/util.hpp"

namespace datadog::impl {

EventStorage::EventStorage(IFilesystem& fs, std::string_view feature_name)
    : _fs(fs), _feature_name(feature_name) {}

bool EventStorage::Initialize(
    const impl::DiagnosticLogger& logger, std::string_view events_root
) {
  PlatformPath path;

  const char* join_message =
      "Failed to initialize event storage: path exceeded length limit";
  const char* mkdir_message =
      "Failed to initialize event storage: could not create directory";

  // <application-storage>/.datadog/<pid>/<instance-name>/<feature> will contain two
  // subdirectories for events generated by (and uploaded on behalf of) the given
  // feature
  if (!JoinPaths(_pending_path, events_root, _feature_name, logger, join_message)) {
    return false;
  }
  if (!EnsureDirectoryExists(_pending_path, path, _fs, logger, mkdir_message)) {
    return false;
  }

  // We've used _pending_path to store the intermediate feature path, so build
  // _granted_path first, then mutate _pending_path

  // <feature>/v1/ is used to contain events that we have consent to upload
  if (!JoinPaths(_granted_path, _pending_path.Get(), "v1", logger, join_message)) {
    return false;
  }
  if (!EnsureDirectoryExists(_granted_path, path, _fs, logger, mkdir_message)) {
    return false;
  }

  // <feature>/intermediate-v1/ is used for events produced while tracking consent is
  // pending
  if (!JoinPaths(
          _pending_path, _pending_path.Get(), "intermediate-v1", logger, join_message
      )) {
    return false;
  }
  if (!EnsureDirectoryExists(_pending_path, path, _fs, logger, mkdir_message)) {
    return false;
  }

  return true;
}

}  // namespace datadog::impl
