// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
//
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025-Present Datadog, Inc.

#pragma once

#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "datadog/core.hpp"

#include "datadog/impl/core/block.hpp"
#include "datadog/impl/diagnostics.hpp"
#include "datadog/impl/platform/clock.hpp"
#include "datadog/impl/storage/filesystem.hpp"
#include "datadog/impl/storage/path.hpp"

namespace datadog::impl {

/**
 * Controls how often we create new batch files, based on both time and size limits.
 */
struct EventStorageConfig {
  /**
   * Once a file exceeds this age, we will not write to it again.
   */
  Duration max_file_age;
  /**
   * If the next write to the current file would cause it to exceed this size (in
   * bytes), we will not write to that file and instead create a new one.
   */
  size_t max_file_size{0x400000};  // 4 MB
  /**
   * Maximum number of events that we will write to a single file. A single write
   * operation may include both metadata and event blocks: i.e. if configured with a
   * maximum of 500 writes, a file will contain no more than 500 TLV Metadata blocks and
   * 500 TLV Event blocks.
   */
  int max_writes_per_file{500};

  explicit EventStorageConfig(Duration in_max_file_age)
      : max_file_age(in_max_file_age) {}

  static EventStorageConfig FromBatchSize(BatchSize batch_size);
};

/**
 * Implements the logic used in the storage thread to commit events to persistent
 * storage for a specific feature.
 *
 * Creates and manages two subdirectories within `<events_root>/<feature_name>/`:
 *
 * - `intermediate-v1`: Events are written here while tracking consent is Pending.
 *   The upload thread never reads from this directory; its contents may be deleted
 *   or moved in response to tracking consent changes.
 *
 * - `v1`: Events are written here while tracking consent is Granted. The upload
 *   thread reads batches from this directory.
 *
 * EventStorage keeps track of the batch file most recently written to, making
 * decisions on each write about when to close the file and start a new one, what
 * to name new files, etc.
 */
class EventStorage {
 public:
  static const char* PENDING_SUBDIRECTORY_NAME;
  static const char* GRANTED_SUBDIRECTORY_NAME;

  explicit EventStorage(
      IFilesystem& fs,
      std::string_view feature_name,
      const DiagnosticLogger& logger,
      TrackingConsent initial_consent,
      const platform::IClock& clock,
      EventStorageConfig config
  );

  /**
   * Closes any open batch file handle on destruction.
   */
  ~EventStorage();

  EventStorage(const EventStorage&) = delete;
  EventStorage& operator=(const EventStorage&) = delete;
  EventStorage(EventStorage&&) = delete;
  EventStorage& operator=(EventStorage&&) = delete;

  /**
   * Creates the feature directory and both consent subdirectories under
   * `events_root`. Must be called once after construction and before any Write or
   * SetConsent calls.
   */
  bool Initialize(std::string_view events_root);

  /**
   * Handles an event generated by a feature, writing it to the appropriate event
   * storage directory based on current tracking consent. Atomic: on success all
   * requested data is written; on failure nothing is written.
   */
  bool Write(Block event, Block event_metadata);

  /**
   * Notifies the storage thread that the SDK's tracking consent value has changed.
   */
  bool SetConsent(TrackingConsent value);

  /**
   * Closes any currently-open batch file, ensuring that the file is readable and
   * deletable by the upload thread. Should be called by the storage thread after it
   * finishes draining its queue, before the upload thread runs.
   */
  void Flush();

 private:
  IFilesystem& _fs;
  std::string _feature_name;
  DiagnosticLogger _logger;
  TrackingConsent _consent;
  StoragePath _pending_path;  // <events_root>/<feature>/intermediate-v1
  StoragePath _granted_path;  // <events_root>/<feature>/v1
  StoragePath _file_path;     // scratch buffer for the current batch file path
  const platform::IClock& _clock;
  EventStorageConfig _config;
  mutable std::vector<std::string> _last_known_filenames;
  PlatformFileHandle _current_file{INVALID_FILE_HANDLE};

  /**
   * Tracks state for the currently-open batch file.
   *
   * We never reopen existing files, so this state is always initialized fresh when
   * a new batch file is started.
   */
  struct FileDetails {
    uint64_t filename_ms{0};
    int num_writes{0};
    size_t num_bytes_written{0};

    void Reset(uint64_t ms) {
      filename_ms = ms;
      num_writes = 0;
      num_bytes_written = 0;
    }
  } _current_file_details;

  std::vector<char> _write_buffer;

  bool DeletePendingBatches();
  bool MigratePendingBatchesToGranted();
  bool WriteEventTo(const StoragePath& dir_path, Block event, Block event_metadata);
  bool PrepareFileForNextWrite(
      const StoragePath& dir_path, Block event, Block event_metadata
  );
  bool CanReuseFileForNextWrite(
      Timestamp current_time, Block event, Block event_metadata
  ) const;
  std::optional<std::pair<uint64_t, std::string>> GetFilenameForNextWrite(
      const StoragePath& dir_path, Timestamp current_time
  ) const;
  bool CacheKnownFilenames(const StoragePath& dir_path) const;
};

}  // namespace datadog::impl
