# Crashpad is part of the Chromium project, and it uses a Google-specific toolchain
# (depot_tools, gclient, gn, ninja) rather than supporting CMake. We have a script in
# tools/bootstrap-crashpad/ that streamlines the process of cloning and building
# crashpad with its natively-supported tools, and we use the ExternalProject module to
# integrate that build process into our CMake build.
include(ExternalProject)

# Our main library target for the C++ SDK (dd_native) will need to link against the
# crashpad_client static lib once it's built. To ensure binary compatibility, we need to
# resolve the relevant details of our CMake build configuration, so that we can produce
# a GN build with the compatible set of options.
get_target_property(DD_COMPILE_OPTIONS dd_native COMPILE_OPTIONS)
get_target_property(DD_LINK_OPTIONS dd_native LINK_OPTIONS)

# Convert lists to pipe-separated strings to avoid shell parsing issues (CMake lists use
# semicolons, which would be expanded to separate arguments). We use pipe '|' as a
# delimiter since it won't appear in compiler flags.
if(DD_COMPILE_OPTIONS)
    string(REPLACE ";" "|" DD_COMPILE_OPTIONS_ENCODED "${DD_COMPILE_OPTIONS}")
else()
    set(DD_COMPILE_OPTIONS_ENCODED "")
endif()
if(DD_LINK_OPTIONS)
    string(REPLACE ";" "|" DD_LINK_OPTIONS_ENCODED "${DD_LINK_OPTIONS}")
else()
    set(DD_LINK_OPTIONS_ENCODED "")
endif()

# Our bootstrap script requires Python3: any interpreter version will do, since we don't
# require any pip packages, and since the crashpad build itself will use the python
# interpreter bundled with depot_tools
find_package(Python3 REQUIRED COMPONENTS Interpreter)

# Declare an ExternalProject target, which we can build in order to bootstrap the
# crashpad repo with all required tools and then build the static library. Note that
# crashpad_external only encapsulates the commands required to download and build
# crashpad; it doesn't tell CMake anything about that build's artifacts or dependencies
# TODO(RUM-12207): Better support for incremental builds
ExternalProject_Add(crashpad_external
    DOWNLOAD_COMMAND ${Python3_EXECUTABLE} ${CMAKE_SOURCE_DIR}/tools/bootstrap-crashpad/main.py install
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ${Python3_EXECUTABLE} -u ${CMAKE_SOURCE_DIR}/tools/bootstrap-crashpad/main.py build
        --no-install
        -c CMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}
        -c CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -c CMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
        -c DD_COMPILE_OPTIONS=${DD_COMPILE_OPTIONS_ENCODED}
        -c DD_LINK_OPTIONS=${DD_LINK_OPTIONS_ENCODED}
    INSTALL_COMMAND ""
    USES_TERMINAL_DOWNLOAD TRUE
    USES_TERMINAL_BUILD TRUE
    BUILD_ALWAYS TRUE
)

function(register_crashpad_artifact custom_target_name path)
    add_custom_command(OUTPUT ${path} DEPENDS crashpad_external)
    add_custom_target(${custom_target_name} DEPENDS ${path})
endfunction()

# Resolve the expected path to crashpad build artifacts that we'll need to consume later
# in the build
set(CRASHPAD_ARTIFACTS_PATH ${CMAKE_SOURCE_DIR}/chromium/crashpad/crashpad/out/Default/obj)
function(set_crashpad_lib_path OUT_VAR relpath name)
  if(WIN32)
    set(${OUT_VAR} "${CRASHPAD_ARTIFACTS_PATH}/${relpath}/${name}.lib" PARENT_SCOPE)
  else()
    set(${OUT_VAR} "${CRASHPAD_ARTIFACTS_PATH}/${relpath}/lib${name}.a" PARENT_SCOPE)
  endif()
endfunction()
function(set_crashpad_exe_path OUT_VAR name)
  if(WIN32)
    set(${OUT_VAR} "${CRASHPAD_ARTIFACTS_PATH}/${name}.exe" PARENT_SCOPE)
  else()
    set(${OUT_VAR} "${CRASHPAD_ARTIFACTS_PATH}/${name}" PARENT_SCOPE)
  endif()
endfunction()

# The 'crashpad_handler' binary must ultimately be deployed alongside final executable
# for any application that integrates the Datadog SDK with Crashpad support: this is a
# separate executable, launched via the Crashpad client, that receives IPC notifications
# from the client when a crash is detected, and that handles processing and uploading
# crash reports
set_crashpad_exe_path(CRASHPAD_HANDLER_EXE_PATH crashpad_handler)
register_crashpad_artifact(crashpad_handler_exe_file ${CRASHPAD_HANDLER_EXE_PATH})

# 'client' is the static lib that we'll link the SDK against in order to get
# crashpad::CrashpadClient et al. into our build. CRASHPAD_CLIENT_LINK_LIBRARIES will
# represent all of the additional linker dependencies required by the client.
set_crashpad_lib_path(CRASHPAD_CLIENT_LIB_PATH client client)
register_crashpad_artifact(crashpad_client_lib_file ${CRASHPAD_CLIENT_LIB_PATH})
set(CRASHPAD_CLIENT_LINK_LIBRARIES "")

# 'util' is a foundational support library required by client: it provides low-level,
# platform-specific utilities used by client et al. On macOS, util depends on
# 'mig_output', which contains code generated by MIG (Mach Interface Generator).
set_crashpad_lib_path(CRASHPAD_UTIL_LIB_PATH util util)
register_crashpad_artifact(crashpad_util_lib_file ${CRASHPAD_UTIL_LIB_PATH})
list(APPEND CRASHPAD_CLIENT_LINK_LIBRARIES ${CRASHPAD_UTIL_LIB_PATH})
if(APPLE)
    set_crashpad_lib_path(CRASHPAD_MIG_OUTPUT_LIB_PATH util mig_output)
    register_crashpad_artifact(crashpad_mig_output_lib_file ${CRASHPAD_MIG_OUTPUT_LIB_PATH})
    list(APPEND CRASHPAD_CLIENT_LINK_LIBRARIES ${CRASHPAD_MIG_OUTPUT_LIB_PATH})
endif()

# 'base' (from mini_chromium) provides platform abstractions and low-level utilities and
# is required by the crashpad client
set_crashpad_lib_path(CRASHPAD_BASE_LIB_PATH third_party/mini_chromium/mini_chromium/base base)
register_crashpad_artifact(crashpad_base_lib_file ${CRASHPAD_BASE_LIB_PATH})
list(APPEND CRASHPAD_CLIENT_LINK_LIBRARIES ${CRASHPAD_BASE_LIB_PATH})

# On macOS, Crashpad requires additional system frameworks
if(APPLE)
    list(APPEND CRASHPAD_CLIENT_LINK_LIBRARIES "-framework CoreFoundation")
    list(APPEND CRASHPAD_CLIENT_LINK_LIBRARIES "-framework CoreGraphics")
    list(APPEND CRASHPAD_CLIENT_LINK_LIBRARIES "-framework CoreText")
    list(APPEND CRASHPAD_CLIENT_LINK_LIBRARIES "-framework IOKit")
    list(APPEND CRASHPAD_CLIENT_LINK_LIBRARIES "-framework Foundation")
    list(APPEND CRASHPAD_CLIENT_LINK_LIBRARIES "-lbsm")
endif()

# Create an IMPORTED CMake target for the client library: depending on crashpad::client
# via target_link_libraries will ensure that the target links against libclient.a and
# all its linker dependencies
add_library(crashpad::client STATIC IMPORTED)
set_target_properties(crashpad::client PROPERTIES
    IMPORTED_LOCATION ${CRASHPAD_CLIENT_LIB_PATH}
    INTERFACE_LINK_LIBRARIES "${CRASHPAD_CLIENT_LINK_LIBRARIES}"
)

# Create an IMPORTED CMake target for the handler executable: we'll use this later in
# order to ensure that the handler is bundled with the application executable
add_executable(crashpad::handler IMPORTED)
set_target_properties(crashpad::handler PROPERTIES
    IMPORTED_LOCATION ${CRASHPAD_HANDLER_EXE_PATH}
)

# Update the main library target for the SDK to link against the crashpad client
target_include_directories(dd_native PRIVATE
    ${CMAKE_SOURCE_DIR}/chromium/crashpad/crashpad
    ${CMAKE_SOURCE_DIR}/chromium/crashpad/crashpad/third_party/mini_chromium/mini_chromium
)
target_link_libraries(dd_native PRIVATE crashpad::client)

# Establish a direct dependency between dd_native and crashpad_external: this ensures
# that CMake will download and build the crashpad source before attempting to compile
# dd_native
add_dependencies(dd_native crashpad_external)
