#!/usr/bin/env python3
# Unless explicitly stated otherwise all files in this repository are licensed under the
# Apache License Version 2.0.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2025-Present Datadog, Inc.
"""
Process and symbolicate crash reports from the Datadog SDK.

This tool parses crash reports generated by the SDK's crash handler, resolves raw memory
addresses to module+offset pairs, and symbolicates them using platform-specific tools
(atos, llvm-symbolizer, addr2line, or dbh).

This tool is provided for testing purposes: it validates that the crash reports produced
by the SDK can be symbolicated as expected. In a production environment, crash reports
are processed by the SDK and uploaded to Datadog intake, and symbolication ultimately
happens on the Datadog backend.

Usage:
    python3 tools/process-crash-report/main.py [crash_report_path] [options]

    If no crash report path is provided, the tool will use the most recent
    crash report from the .crashes/ directory.

Options:
    --output {full|stack|raw|json}  Output mode (default: full)
                                    - full: metadata + resolved + symbolicated
                                    - stack: symbolicated stack only
                                    - raw: parsed binary without resolution
                                    - json: RUM Error Event JSON object (requires
                                            a RUM application ID in the .ctx file)

    --tool {atos|llvm-symbolizer|addr2line|dbh|none|auto}
                                    Symbolication tool (default: auto)
                                    - auto: platform default
                                    - none: no symbolication (resolved only)
                                    - ignored in raw mode

Examples:
    # Process latest crash with default settings
    python3 tools/process-crash-report/main.py

    # Process specific crash report
    python3 tools/process-crash-report/main.py .crashes/crash_1770922852158_10798

    # Show only symbolicated stack (no metadata)
    python3 tools/process-crash-report/main.py --output stack

    # Show raw parsed binary crash report (no resolution/symbolication)
    python3 tools/process-crash-report/main.py --output raw

    # Use specific symbolication tool
    python3 tools/process-crash-report/main.py --tool llvm-symbolizer

    # Show resolved addresses without symbolication
    python3 tools/process-crash-report/main.py --tool none

    # Emit a RUM Error Event JSON object
    python3 tools/process-crash-report/main.py --output json
"""

import json
import sys
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from pathlib import Path

# Import lib modules
from lib.parser import find_latest_crash_report, load_crash_report, parse_crash_report, parse_crash_context
from lib.symbolizers import get_symbolizer, SymbolizerTool
from lib.formatters import print_crash_report, print_raw_crash_report, format_rum_error_event, OutputMode


def main() -> int:
    """Main entry point."""
    # === Argument Parsing ===
    parser = ArgumentParser(
        description='Process and symbolicate crash reports',
        formatter_class=RawDescriptionHelpFormatter,
        epilog=__doc__.split('Examples:')[1] if 'Examples:' in __doc__ else None
    )

    parser.add_argument(
        'crash_report',
        nargs='?',
        type=Path,
        help='Path to crash report (default: most recent in .crashes/)'
    )

    parser.add_argument(
        '--output',
        choices=['full', 'stack', 'raw', 'json'],
        default='full',
        help='Output mode: full (metadata + stacks), stack (symbolicated only), raw (parsed binary), or json (RUM Error Event)'
    )

    parser.add_argument(
        '--tool',
        choices=['atos', 'llvm-symbolizer', 'addr2line', 'dbh', 'none', 'auto'],
        default='auto',
        help='Symbolication tool (default: auto = platform default)'
    )

    args = parser.parse_args()

    # === Resolve Crash Report Path ===
    crash_report_path: Path

    if args.crash_report:
        # Explicit path provided
        crash_report_path = args.crash_report
        if not crash_report_path.exists():
            print(f"Error: Crash report not found: {crash_report_path}", file=sys.stderr)
            return 1
    else:
        # Find latest crash report in .crashes/
        crashes_dir = Path('.crashes')
        crash_report_path = find_latest_crash_report(crashes_dir)

        if crash_report_path is None:
            print("Error: No crash reports found in .crashes/", file=sys.stderr)
            print("", file=sys.stderr)
            print("Generate a crash report by running a program that uses the SDK", file=sys.stderr)
            print("and triggers a crash (e.g., dd_native_repl with a crash command).", file=sys.stderr)
            return 1

    # === Handle Raw Output Mode ===
    # Raw mode: parse binary but skip resolution/symbolication (--tool ignored)
    if args.output == 'raw':
        try:
            metadata, stack_addresses, modules = parse_crash_report(crash_report_path)
            rum_context = parse_crash_context(crash_report_path.with_suffix('.ctx'))
            print_raw_crash_report(crash_report_path, metadata, stack_addresses, modules, rum_context)
            return 0
        except FileNotFoundError as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1
        except ValueError as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1
        except Exception as e:
            print(f"Error parsing crash report: {e}", file=sys.stderr)
            return 1

    # === Parse Crash Report ===
    try:
        report = load_crash_report(crash_report_path)
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Error parsing crash report: {e}", file=sys.stderr)
        return 1

    # === Get Symbolizer ===
    symbolized_stack = None

    tool_enum = SymbolizerTool(args.tool)

    if tool_enum != SymbolizerTool.NONE:
        try:
            symbolizer = get_symbolizer(tool_enum)

            if symbolizer is not None:
                # Symbolicate the stack
                symbolized_stack = symbolizer.symbolicate_stack(report.stack_frames)

        except RuntimeError as e:
            # Tool not available - fail fast with helpful error
            print(f"Error: {e}", file=sys.stderr)
            return 1
        except Exception as e:
            print(f"Error during symbolication: {e}", file=sys.stderr)
            return 1

    # === Print Output ===
    output_mode = OutputMode(args.output)

    try:
        if output_mode == OutputMode.JSON:
            event = format_rum_error_event(report, symbolized_stack)
            print(json.dumps(event, separators=(',', ':')))
        else:
            print_crash_report(report, symbolized_stack, output_mode)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"Error formatting output: {e}", file=sys.stderr)
        return 1

    return 0


if __name__ == '__main__':
    sys.exit(main())
